### ISSUE TITLE
Is there also a C++ version for the Ion IAP encoding ?

### ISSUE THREAD

**Issue by vortex314** [jjenkov/iap-tools-java-benchmarks#1]
Hi Jakob,
I enjoyed reading your article on performance benchmarks for this encoding. I was wondering if there is also somewhere a c++ implementation of this ? I'm interested as I tinker with microcontrollers and am implementing an inter-task communication with high-speed serialization,de-serialization in memory. 

regards
Lieven

**Comment by jjenkov** [comment]
Sorry about this very late reply. No, at this point there is only a Java version of IAP / RION .
